CREATE DATABASE IF NOT EXISTS idealink CHARACTER SET utf8mb4;
USE idealink;
CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) UNIQUE NOT NULL, pw VARCHAR(255) NOT NULL,
 private_id VARCHAR(12) UNIQUE NOT NULL, nickname VARCHAR(40) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ideas(id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(140) NOT NULL, statement TEXT NOT NULL,
 tags VARCHAR(200) DEFAULT '', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id),
 FULLTEXT(title,statement));
CREATE TABLE connections(id INT AUTO_INCREMENT PRIMARY KEY, from_user INT NOT NULL, to_user INT NOT NULL, idea_id INT NOT NULL,
 status ENUM('pending','accepted') DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(from_user,to_user,idea_id), FOREIGN KEY(from_user) REFERENCES users(id), FOREIGN KEY(to_user) REFERENCES users(id));
CREATE TABLE messages(id INT AUTO_INCREMENT PRIMARY KEY, conn_id INT NOT NULL, sender_id INT NOT NULL, body TEXT NOT NULL,
 sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(conn_id) REFERENCES connections(id));
CREATE TABLE projects(id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, title VARCHAR(140) NOT NULL, description TEXT NOT NULL,
 views INT DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE likes(project_id INT, user_id INT, PRIMARY KEY(project_id,user_id));
CREATE TABLE tickets(id INT AUTO_INCREMENT PRIMARY KEY, user_id INT NOT NULL, category VARCHAR(30) NOT NULL, subject VARCHAR(140) NOT NULL,
 details TEXT NOT NULL, status ENUM('open','in_review','resolved') DEFAULT 'open', reply TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id));
